apiVersion: apps/v1
kind: Deployment
metadata:
  name: warbler-deployment
  labels:
    app: warbler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warbler
  template:
    metadata:
      labels:
        app: warbler
    spec:
      containers:
      - name: warbler
        image: mstergianis/warbler:0.0.1a
        env:
        - name: POSTGRES_HOST
          value: <YOUR HOST>
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
