apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <YOUR SERVER>
    path: "/path/to/your/library"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-nfs-pvc
spec:
  resources:
    requests:
      storage: 1Ti
  accessModes:
  - ReadWriteMany
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warbler-deployment
  labels:
    app: warbler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warbler
  template:
    metadata:
      labels:
        app: warbler
    spec:
      containers:
      - name: warbler
        image: mstergianis/warbler:0.0.2a
        volumeMounts:
        - name: music-lib
          mountPath: "/app/music"
        env:
        - name: POSTGRES_HOST
          value: <YOUR HOST>
        ports:
        - containerPort: 8080
      volumes:
        - name: music-lib
          persistentVolumeClaim:
            claimName: music-nfs-pvc
      imagePullSecrets:
      - name: regcred
